# YAML Lint configuration
extends: default

rules:
  # Disable context validation warnings for GitHub Actions
  # These are handled by GitHub's own validation
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 120
  indentation:
    spaces: 2
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']

# Ignore GitHub Actions context expressions
ignore: |
  .github/workflows/*.yml
  .github/workflows/*.yaml