AWSTemplateFormatVersion: '2010-09-09'
Description: Quilt MCP server Fargate service with ALB listener rule, target group, and runtime secrets.

Parameters:
  ServiceName:
    Type: String
    Default: quilt-mcp-server
  VpcId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>
  AlbSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  AlbListenerArn:
    Type: String
  ListenerHost:
    Type: String
  ListenerPath:
    Type: String
    Default: /mcp/*
  ClusterArn:
    Type: String
  ContainerImage:
    Type: String
  ContainerPort:
    Type: Number
    Default: 8000
  DesiredCount:
    Type: Number
    Default: 1
  ExecutionRoleArn:
    Type: String
  JwtSecretArn:
    Type: String
  JwtKidArn:
    Type: String
  LogRetentionInDays:
    Type: Number
    Default: 30
  HealthCheckPath:
    Type: String
    Default: /healthz

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${ServiceName}"
      RetentionInDays: !Ref LogRetentionInDays

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Description: IAM role used by the Quilt MCP ECS task

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref ServiceName
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '512'
      Memory: '1024'
      ExecutionRoleArn: !Ref ExecutionRoleArn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Image: !Ref ContainerImage
          Essential: true
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              HostPort: !Ref ContainerPort
              Protocol: tcp
          Environment:
            - Name: FASTMCP_TRANSPORT
              Value: http
            - Name: FASTMCP_HOST
              Value: 0.0.0.0
            - Name: FASTMCP_PORT
              Value: !Sub "${ContainerPort}"
          Secrets:
            - Name: MCP_ENHANCED_JWT_SECRET
              ValueFrom: !Ref JwtSecretArn
            - Name: MCP_ENHANCED_JWT_KID
              ValueFrom: !Ref JwtKidArn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          HealthCheck:
            Command:
              - CMD-SHELL
              - !Sub "curl -f http://127.0.0.1:${ContainerPort}${HealthCheckPath} || exit 1"
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60

  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "Security group for ${ServiceName}"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          SourceSecurityGroupId: !Ref AlbSecurityGroupId
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${ServiceName}-tg"
      Port: !Ref ContainerPort
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckProtocol: HTTP
      Matcher:
        HttpCode: 200-399

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref AlbListenerArn
      Priority: 100
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !Ref ListenerHost
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - !Ref ListenerPath

  Service:
    Type: AWS::ECS::Service
    DependsOn:
      - ListenerRule
    Properties:
      ServiceName: !Ref ServiceName
      Cluster: !Ref ClusterArn
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      PlatformVersion: LATEST
      TaskDefinition: !Ref TaskDefinition
      EnableExecuteCommand: false
      LoadBalancers:
        - ContainerName: !Ref ServiceName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: !Ref PrivateSubnets
          SecurityGroups:
            - !Ref ServiceSecurityGroup
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      DeploymentCircuitBreaker:
        Enable: true
        Rollback: true

Outputs:
  ServiceName:
    Description: Name of the ECS service
    Value: !Ref ServiceName
  TargetGroupArn:
    Description: ARN of the ALB target group
    Value: !Ref TargetGroup
