apiVersion: v1
kind: Secret
metadata:
  name: quilt-mcp-jwt
type: Opaque
stringData:
  MCP_JWT_SECRET: "replace-me"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quilt-mcp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quilt-mcp
  template:
    metadata:
      labels:
        app: quilt-mcp
    spec:
      containers:
        - name: quilt-mcp
          image: quiltdata/quilt-mcp:latest
          ports:
            - containerPort: 8000
          env:
            - name: MCP_REQUIRE_JWT
              value: "true"
            - name: QUILT_CATALOG_URL
              value: "https://your-catalog.quiltdata.com"
            - name: QUILT_REGISTRY_URL
              value: "https://registry.your-catalog.quiltdata.com"
            - name: MCP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: quilt-mcp-jwt
                  key: MCP_JWT_SECRET
