[project]
name = "quilt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.12.4",
    "pytest>=8.4.1",
    "quilt3>=6.3.1",
]

[project.optional-dependencies]
test = [
    "pytest>=8.0.0",
]
