name: 'Create Release'
description: 'Build Python package, MCPB package, Docker image, and create GitHub release'
inputs:
  package-version:
    description: 'Version from git tag (e.g., 0.5.9-dev-20250904075318)'
    required: true
  pypi-repository-url:
    description: 'PyPI repository URL (empty for PyPI, https://test.pypi.org/legacy/ for TestPyPI)'
    required: false
    default: ''
  skip-existing:
    description: 'Skip existing packages during upload'
    required: false
    default: 'false'
  build-docker:
    description: 'Build and push Docker image (true/false)'
    required: false
    default: 'true'

outputs:
  release-url:
    description: 'URL of the created release'
    value: ${{ steps.create-release.outputs.url }}

runs:
  using: 'composite'
  steps:
    - name: Install build dependencies
      shell: bash
      run: uv sync --group dev

    - name: Build python distributions
      shell: bash
      run: make python-dist

    - name: Publish to PyPI/TestPyPI
      uses: pypa/gh-action-pypi-publish@ec4db0b4ddc65acdf4bff5fa45ac92d78b56bdf0
      with:
        repository-url: ${{ inputs.pypi-repository-url }}
        packages-dir: dist/
        skip-existing: ${{ inputs.skip-existing }}
        verbose: true

    - name: Build MCPB package
      shell: bash
      run: make mcpb

    - name: Validate MCPB package
      shell: bash
      run: make mcpb-validate

    - name: Create release bundle
      shell: bash
      run: make release-zip

    - name: Build and push Docker image
      if: ${{ inputs.build-docker == 'true' }}
      shell: bash
      env:
        VERSION: ${{ inputs.package-version }}
        ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
        AWS_ACCOUNT_ID: ${{ env.AWS_ACCOUNT_ID }}
        AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
      run: |
        echo "🐳 Building and pushing Docker image with scripts/docker.sh"
        chmod +x scripts/docker.sh
        ./scripts/docker.sh push --version "$VERSION"

    - name: Create GitHub Release
      id: create-release
      uses: softprops/action-gh-release@v2
      with:
        name: "Quilt MCP MCPB v${{ inputs.package-version }}"
        files: |
          dist/*.mcpb
          dist/*-release.zip
        draft: false
        prerelease: ${{ contains(inputs.package-version, '-') }}
        generate_release_notes: true

    - name: Upload MCPB artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mcpb-package
        path: dist/*.mcpb
        retention-days: 90