name: 'Create Release'
description: 'Build DXT package and create GitHub release with bundle'
inputs:
  tag-version:
    description: 'Version from git tag (e.g., 0.5.9-dev-20250904075318)'
    required: true
  pypi-token:
    description: 'API token used for publishing via PyPA action'
    required: true
  pypi-repository-url:
    description: 'Repository endpoint for PyPA publish'
    required: false
    default: 'https://upload.pypi.org/legacy/'

outputs:
  release-url:
    description: 'URL of the created release'
    value: ${{ steps.create-release.outputs.url }}

runs:
  using: 'composite'
  steps:
    - name: Build python distributions
      shell: bash
      run: ./bin/release.sh python-dist

    - name: Publish to PyPI/TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ inputs.pypi-token }}
        repository-url: ${{ inputs.pypi-repository-url }}
        packages-dir: dist/

    - name: Build DXT package
      shell: bash
      run: make dxt

    - name: Validate DXT package
      shell: bash
      run: make dxt-validate

    - name: Create release bundle
      shell: bash
      run: make release-zip

    - name: Create GitHub Release
      id: create-release
      uses: softprops/action-gh-release@v2
      with:
        name: "Quilt MCP DXT v${{ inputs.tag-version }}"
        files: |
          dist/*-release.zip
        draft: false
        prerelease: ${{ contains(inputs.tag-version, '-') }}
        generate_release_notes: true
        
    - name: Upload DXT artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dxt-package
        path: dist/*.dxt
        retention-days: 90

    - name: Upload Python distributions
      uses: actions/upload-artifact@v4
      with:
        name: python-dist
        path: |
          dist/*.whl
          dist/*.tar.gz
        retention-days: 14
