name: 'Create Release'
description: 'Build Python package, DXT package, and create GitHub release'
inputs:
  package-version:
    description: 'Version from git tag (e.g., 0.5.9-dev-20250904075318)'
    required: true
  pypi-repository-url:
    description: 'PyPI repository URL (empty for PyPI, https://test.pypi.org/legacy/ for TestPyPI)'
    required: false
    default: ''
  skip-existing:
    description: 'Skip existing packages during upload'
    required: false
    default: 'false'

outputs:
  release-url:
    description: 'URL of the created release'
    value: ${{ steps.create-release.outputs.url }}

runs:
  using: 'composite'
  steps:
    - name: Build python distributions
      shell: bash
      run: ./bin/release.sh python-dist

    - name: Publish to PyPI/TestPyPI
      uses: pypa/gh-action-pypi-publish@ec4db0b4ddc65acdf4bff5fa45ac92d78b56bdf0
      with:
        repository-url: ${{ inputs.pypi-repository-url }}
        packages-dir: dist/
        skip-existing: ${{ inputs.skip-existing }}
        verbose: true

    - name: Build DXT package
      shell: bash
      run: make dxt

    - name: Validate DXT package
      shell: bash
      run: make dxt-validate

    - name: Create release bundle
      shell: bash
      run: make release-zip

    - name: Create GitHub Release
      id: create-release
      uses: softprops/action-gh-release@v2
      with:
        name: "Quilt MCP DXT v${{ inputs.package-version }}"
        files: |
          dist/*-release.zip
        draft: false
        prerelease: ${{ contains(inputs.package-version, '-') }}
        generate_release_notes: true

    - name: Upload DXT artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dxt-package
        path: dist/*.dxt
        retention-days: 90