name: 'Setup Build Environment'
description: 'Common setup steps for Python and Node.js build environment'
inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.11'
  include-nodejs:
    description: 'Whether to include Node.js setup'
    required: false
    default: 'false'
  nodejs-version:
    description: 'Node.js version to install'
    required: false
    default: '18'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Set up Python
      shell: bash
      run: uv python install ${{ inputs.python-version }}
      
    - name: Set up Node.js
      if: inputs.include-nodejs == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.nodejs-version }}
      
    - name: Install DXT CLI
      if: inputs.include-nodejs == 'true'
      shell: bash
      run: npm install -g @anthropic-ai/dxt
      
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          ~/.npm
        key: ${{ runner.os }}-deps-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-deps-