"""Pydantic models for structured, type-safe MCP tool inputs and responses."""

from .inputs import (
    # Athena input models
    AthenaQueryExecuteParams,
    AthenaQueryValidateParams,
    # Bucket input models
    BucketObjectFetchParams,
    BucketObjectInfoParams,
    BucketObjectLinkParams,
    BucketObjectTextParams,
    BucketObjectsPutItem,
    BucketObjectsPutParams,
    BucketObjectsListParams,
    # Catalog input models
    CatalogUriParams,
    CatalogUrlParams,
    # Data visualization input models
    DataVisualizationParams,
    # Package input models
    PackageBrowseParams,
    PackageCreateParams,
    PackageCreateFromS3Params,
    PackageDeleteParams,
    PackageDiffParams,
    PackagesListParams,
    PackageUpdateParams,
    # Workflow input models
    WorkflowAddStepParams,
    WorkflowCreateParams,
    WorkflowUpdateStepParams,
)
from .responses import (
    # Base responses
    ErrorResponse,
    SuccessResponse,
    # Catalog responses
    CatalogUriError,
    CatalogUriResponse,
    CatalogUriSuccess,
    CatalogUrlError,
    CatalogUrlResponse,
    CatalogUrlSuccess,
    # Bucket responses
    BucketObjectInfoError,
    BucketObjectInfoResponse,
    BucketObjectInfoSuccess,
    BucketObjectsListError,
    BucketObjectsListResponse,
    BucketObjectsListSuccess,
    BucketObjectTextSuccess,
    BucketObjectTextError,
    BucketObjectTextResponse,
    BucketObjectFetchSuccess,
    BucketObjectFetchError,
    BucketObjectFetchResponse,
    BucketObjectsPutSuccess,
    BucketObjectsPutError,
    BucketObjectsPutResponse,
    ObjectMetadata,
    PresignedUrlResponse,
    S3Object,
    UploadResult,
    # Package responses
    PackageBrowseResponse,
    PackageBrowseSuccess,
    PackageCreateError,
    PackageCreateResponse,
    PackageCreateSuccess,
    PackageCreateFromS3Error,
    PackageCreateFromS3Response,
    PackageCreateFromS3Success,
    PackageDeleteError,
    PackageDeleteResponse,
    PackageDeleteSuccess,
    PackageDiffError,
    PackageDiffResponse,
    PackageDiffSuccess,
    PackageFileEntry,
    PackageMetadata,
    PackagesListError,
    PackageSummary,
    PackagesListResponse,
    PackagesListSuccess,
    PackageUpdateError,
    PackageUpdateResponse,
    PackageUpdateSuccess,
    # Athena responses
    AthenaQueryError,
    AthenaQueryResponse,
    AthenaQuerySuccess,
    AthenaQueryValidationError,
    AthenaQueryValidationResponse,
    AthenaQueryValidationSuccess,
    QueryExecutionMetadata,
    # Visualization responses
    DataVisualizationError,
    DataVisualizationResponse,
    DataVisualizationSuccess,
    VisualizationConfig,
    VisualizationFile,
    # Workflow responses
    WorkflowCreateResponse,
    WorkflowCreateSuccess,
    WorkflowStep,
    WorkflowStepUpdateResponse,
    WorkflowStepUpdateSuccess,
)

__all__ = [
    # Input models - Athena
    "AthenaQueryExecuteParams",
    "AthenaQueryValidateParams",
    # Input models - Bucket
    "BucketObjectFetchParams",
    "BucketObjectInfoParams",
    "BucketObjectLinkParams",
    "BucketObjectTextParams",
    "BucketObjectsPutItem",
    "BucketObjectsPutParams",
    "BucketObjectsListParams",
    # Input models - Catalog
    "CatalogUriParams",
    "CatalogUrlParams",
    # Input models - Data visualization
    "DataVisualizationParams",
    # Input models - Package
    "PackageBrowseParams",
    "PackageCreateParams",
    "PackageCreateFromS3Params",
    "PackageDeleteParams",
    "PackageDiffParams",
    "PackagesListParams",
    "PackageUpdateParams",
    # Input models - Workflow
    "WorkflowAddStepParams",
    "WorkflowCreateParams",
    "WorkflowUpdateStepParams",
    # Response models - Base
    "ErrorResponse",
    "SuccessResponse",
    # Catalog
    "CatalogUriError",
    "CatalogUriResponse",
    "CatalogUriSuccess",
    "CatalogUrlError",
    "CatalogUrlResponse",
    "CatalogUrlSuccess",
    # Bucket
    "BucketObjectInfoError",
    "BucketObjectInfoResponse",
    "BucketObjectInfoSuccess",
    "BucketObjectsListError",
    "BucketObjectsListResponse",
    "BucketObjectsListSuccess",
    "BucketObjectTextSuccess",
    "BucketObjectTextError",
    "BucketObjectTextResponse",
    "BucketObjectFetchSuccess",
    "BucketObjectFetchError",
    "BucketObjectFetchResponse",
    "BucketObjectsPutSuccess",
    "BucketObjectsPutError",
    "BucketObjectsPutResponse",
    "ObjectMetadata",
    "PresignedUrlResponse",
    "S3Object",
    "UploadResult",
    # Package
    "PackageBrowseResponse",
    "PackageBrowseSuccess",
    "PackageCreateError",
    "PackageCreateResponse",
    "PackageCreateSuccess",
    "PackageCreateFromS3Error",
    "PackageCreateFromS3Response",
    "PackageCreateFromS3Success",
    "PackageDeleteError",
    "PackageDeleteResponse",
    "PackageDeleteSuccess",
    "PackageDiffError",
    "PackageDiffResponse",
    "PackageDiffSuccess",
    "PackageFileEntry",
    "PackageMetadata",
    "PackagesListError",
    "PackageSummary",
    "PackagesListResponse",
    "PackagesListSuccess",
    "PackageUpdateError",
    "PackageUpdateResponse",
    "PackageUpdateSuccess",
    # Athena
    "AthenaQueryError",
    "AthenaQueryResponse",
    "AthenaQuerySuccess",
    "AthenaQueryValidationError",
    "AthenaQueryValidationResponse",
    "AthenaQueryValidationSuccess",
    "QueryExecutionMetadata",
    # Visualization
    "DataVisualizationError",
    "DataVisualizationResponse",
    "DataVisualizationSuccess",
    "VisualizationConfig",
    "VisualizationFile",
    # Workflow
    "WorkflowCreateResponse",
    "WorkflowCreateSuccess",
    "WorkflowStep",
    "WorkflowStepUpdateResponse",
    "WorkflowStepUpdateSuccess",
]
