"""Pydantic models for structured, type-safe MCP tool inputs and responses."""

from .responses import (
    # Base responses
    ErrorResponse,
    SuccessResponse,
    # Catalog responses
    CatalogUriError,
    CatalogUriResponse,
    CatalogUriSuccess,
    CatalogUrlError,
    CatalogUrlResponse,
    CatalogUrlSuccess,
    # Bucket responses
    BucketObjectInfoError,
    BucketObjectInfoResponse,
    BucketObjectInfoSuccess,
    BucketObjectsListError,
    BucketObjectsListResponse,
    BucketObjectsListSuccess,
    BucketObjectTextSuccess,
    BucketObjectTextError,
    BucketObjectTextResponse,
    BucketObjectFetchSuccess,
    BucketObjectFetchError,
    BucketObjectFetchResponse,
    BucketObjectsPutSuccess,
    BucketObjectsPutError,
    BucketObjectsPutResponse,
    ObjectMetadata,
    PresignedUrlResponse,
    S3Object,
    UploadResult,
    # Package responses
    PackageBrowseResponse,
    PackageBrowseSuccess,
    PackageCreateError,
    PackageCreateResponse,
    PackageCreateSuccess,
    PackageCreateFromS3Error,
    PackageCreateFromS3Response,
    PackageCreateFromS3Success,
    PackageDeleteError,
    PackageDeleteResponse,
    PackageDeleteSuccess,
    PackageDiffError,
    PackageDiffResponse,
    PackageDiffSuccess,
    PackageFileEntry,
    PackageMetadata,
    PackagesListError,
    PackageSummary,
    PackagesListResponse,
    PackagesListSuccess,
    PackageUpdateError,
    PackageUpdateResponse,
    PackageUpdateSuccess,
    # Athena responses
    AthenaDatabasesListResponse,
    AthenaDatabasesListSuccess,
    AthenaQueryError,
    AthenaQueryHistoryResponse,
    AthenaQueryHistorySuccess,
    AthenaQueryResponse,
    AthenaQuerySuccess,
    AthenaQueryValidationError,
    AthenaQueryValidationResponse,
    AthenaQueryValidationSuccess,
    AthenaTableSchemaResponse,
    AthenaTableSchemaSuccess,
    AthenaTablesListResponse,
    AthenaTablesListSuccess,
    AthenaWorkgroupsListResponse,
    AthenaWorkgroupsListSuccess,
    ColumnInfo,
    DatabaseInfo,
    PartitionInfo,
    QueryExecutionMetadata,
    QueryHistoryEntry,
    TableInfo,
    TableSchemaInfo,
    WorkgroupInfo,
    # Visualization responses
    DataVisualizationError,
    DataVisualizationResponse,
    DataVisualizationSuccess,
    VisualizationConfig,
    VisualizationFile,
    # Workflow responses
    WorkflowAddStepResponse,
    WorkflowAddStepSuccess,
    WorkflowCreateResponse,
    WorkflowCreateSuccess,
    WorkflowGetStatusResponse,
    WorkflowGetStatusSuccess,
    WorkflowListAllResponse,
    WorkflowListAllSuccess,
    WorkflowProgress,
    WorkflowStep,
    WorkflowStepUpdateResponse,
    WorkflowStepUpdateSuccess,
    WorkflowSummary,
    WorkflowTemplateApplyResponse,
    WorkflowTemplateApplySuccess,
    # Error recovery responses
    HealthCheckSuccess,
    # Quilt summary responses
    QuiltSummarizeJson,
    QuiltSummarizeJsonError,
    QuiltSummarizeJsonResponse,
    PackageVisualizationsSuccess,
    PackageVisualizationsError,
    PackageVisualizationsResponse,
    QuiltSummaryFilesSuccess,
    QuiltSummaryFilesError,
    QuiltSummaryFilesResponse,
    # Search responses
    SearchExplainSuccess,
    SearchExplainError,
    SearchExplainResponse,
    SearchGraphQLSuccess,
    SearchGraphQLError,
    SearchGraphQLResponse,
)

__all__ = [
    # Response models - Base
    "ErrorResponse",
    "SuccessResponse",
    # Catalog
    "CatalogUriError",
    "CatalogUriResponse",
    "CatalogUriSuccess",
    "CatalogUrlError",
    "CatalogUrlResponse",
    "CatalogUrlSuccess",
    # Bucket
    "BucketObjectInfoError",
    "BucketObjectInfoResponse",
    "BucketObjectInfoSuccess",
    "BucketObjectsListError",
    "BucketObjectsListResponse",
    "BucketObjectsListSuccess",
    "BucketObjectTextSuccess",
    "BucketObjectTextError",
    "BucketObjectTextResponse",
    "BucketObjectFetchSuccess",
    "BucketObjectFetchError",
    "BucketObjectFetchResponse",
    "BucketObjectsPutSuccess",
    "BucketObjectsPutError",
    "BucketObjectsPutResponse",
    "ObjectMetadata",
    "PresignedUrlResponse",
    "S3Object",
    "UploadResult",
    # Package
    "PackageBrowseResponse",
    "PackageBrowseSuccess",
    "PackageCreateError",
    "PackageCreateResponse",
    "PackageCreateSuccess",
    "PackageCreateFromS3Error",
    "PackageCreateFromS3Response",
    "PackageCreateFromS3Success",
    "PackageDeleteError",
    "PackageDeleteResponse",
    "PackageDeleteSuccess",
    "PackageDiffError",
    "PackageDiffResponse",
    "PackageDiffSuccess",
    "PackageFileEntry",
    "PackageMetadata",
    "PackagesListError",
    "PackageSummary",
    "PackagesListResponse",
    "PackagesListSuccess",
    "PackageUpdateError",
    "PackageUpdateResponse",
    "PackageUpdateSuccess",
    # Athena
    "AthenaDatabasesListResponse",
    "AthenaDatabasesListSuccess",
    "AthenaQueryError",
    "AthenaQueryHistoryResponse",
    "AthenaQueryHistorySuccess",
    "AthenaQueryResponse",
    "AthenaQuerySuccess",
    "AthenaQueryValidationError",
    "AthenaQueryValidationResponse",
    "AthenaQueryValidationSuccess",
    "AthenaTableSchemaResponse",
    "AthenaTableSchemaSuccess",
    "AthenaTablesListResponse",
    "AthenaTablesListSuccess",
    "AthenaWorkgroupsListResponse",
    "AthenaWorkgroupsListSuccess",
    "ColumnInfo",
    "DatabaseInfo",
    "PartitionInfo",
    "QueryExecutionMetadata",
    "QueryHistoryEntry",
    "TableInfo",
    "TableSchemaInfo",
    "WorkgroupInfo",
    # Visualization
    "DataVisualizationError",
    "DataVisualizationResponse",
    "DataVisualizationSuccess",
    "VisualizationConfig",
    "VisualizationFile",
    # Workflow
    "WorkflowAddStepResponse",
    "WorkflowAddStepSuccess",
    "WorkflowCreateResponse",
    "WorkflowCreateSuccess",
    "WorkflowGetStatusResponse",
    "WorkflowGetStatusSuccess",
    "WorkflowListAllResponse",
    "WorkflowListAllSuccess",
    "WorkflowProgress",
    "WorkflowStep",
    "WorkflowStepUpdateResponse",
    "WorkflowStepUpdateSuccess",
    "WorkflowSummary",
    "WorkflowTemplateApplyResponse",
    "WorkflowTemplateApplySuccess",
    # Error recovery
    "HealthCheckSuccess",
    # Quilt summary
    "QuiltSummarizeJson",
    "QuiltSummarizeJsonError",
    "QuiltSummarizeJsonResponse",
    "PackageVisualizationsSuccess",
    "PackageVisualizationsError",
    "PackageVisualizationsResponse",
    "QuiltSummaryFilesSuccess",
    "QuiltSummaryFilesError",
    "QuiltSummaryFilesResponse",
    # Search
    "SearchExplainSuccess",
    "SearchExplainError",
    "SearchExplainResponse",
    "SearchGraphQLSuccess",
    "SearchGraphQLError",
    "SearchGraphQLResponse",
]
