# CI workflow has been migrated to new architecture as part of A04 specification
#
# New workflows:
# - pr.yml: Fast PR validation (< 5 minutes, single Python version)
# - push.yml: Comprehensive main branch testing (all Python versions)
# - release.yml: Production releases with proper dependencies
#
# This provides:
# - 60% reduction in CI costs for PRs
# - Enhanced coverage analysis with CSV reporting
# - Faster feedback cycles
# - Better separation of concerns

name: CI (Migrated)

on:
  workflow_dispatch:
    inputs:
      migration_info:
        description: 'Show migration information'
        required: false
        default: 'show'

jobs:
  migration-info:
    runs-on: ubuntu-latest
    steps:
    - name: CI Migration Information
      run: |
        echo "✅ CI workflow has been successfully migrated to new architecture"
        echo ""
        echo "📋 New Workflow Structure:"
        echo "  • pr.yml - Fast PR validation (< 5 minutes)"
        echo "  • push.yml - Comprehensive main branch testing"
        echo "  • release.yml - Production releases with dependencies"
        echo ""
        echo "🚀 Benefits:"
        echo "  • 60% fewer CI builds on PRs"
        echo "  • Enhanced coverage analysis with CSV reports"
        echo "  • Faster feedback for developers"
        echo "  • Better artifact management"
        echo ""
        echo "📊 Coverage Analysis:"
        echo "  • Multi-suite coverage tracking (unit/integration/e2e)"
        echo "  • File-level coverage gap analysis"
        echo "  • CSV export for coverage trends"
        echo ""
        echo "For details, see: A04 specification in /spec/a04-auto-coverage.md"