name: Build and Release DXT

# This workflow builds the Quilt MCP DXT package and creates a GitHub release
# with the .dxt file and accompanying documentation for version tags.
# For feature branches, it builds and uploads DXT files as artifacts for testing.
# The DXT build only runs after all tests pass successfully.

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0)
    branches:
      - 'feature/s3-to-package-creation'  # Build DXT for S3-to-package feature branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  # Run tests first to ensure quality
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build-and-release:
    runs-on: ubuntu-latest
    needs: test  # Only run DXT build if tests pass
    permissions:
      contents: write  # Required for creating releases
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Set up Python
      run: uv python install 3.11
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Extract version from tag
      id: version
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
          IS_RELEASE=true
        elif [[ "${{ github.ref }}" == refs/heads/feature/* ]]; then
          VERSION="dev-$(echo ${{ github.ref_name }} | sed 's/feature\///' | sed 's/\//-/g')-$(date +%Y%m%d-%H%M%S)"
          IS_RELEASE=false
        else
          VERSION="0.0.0-dev"
          IS_RELEASE=false
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "is_release=$IS_RELEASE" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"
        echo "Is Release: $IS_RELEASE"
        
    - name: Build DXT package
      run: |
        echo "🔨 Building DXT package..."
        cd build-dxt
        make build VERSION=${{ steps.version.outputs.version }}
        
        # Verify the DXT was built
        ls -la dist/
        echo "✅ DXT package built successfully"
        
    - name: Test DXT package
      run: |
        echo "🧪 Testing DXT package..."
        cd build-dxt
        make test VERSION=${{ steps.version.outputs.version }}
        echo "✅ DXT package tested successfully"
        
    - name: Upload DXT artifact for feature branches
      if: steps.version.outputs.is_release == 'false'
      uses: actions/upload-artifact@v4
      with:
        name: quilt-mcp-${{ steps.version.outputs.version }}-dxt
        path: build-dxt/dist/quilt-mcp-${{ steps.version.outputs.version }}.dxt
        retention-days: 30
        
    - name: Prepare release assets
      if: steps.version.outputs.is_release == 'true'
      run: |
        echo "📦 Preparing release assets..."
        mkdir -p release-assets
        
        # Copy DXT file
        cp build-dxt/dist/quilt-mcp-${{ steps.version.outputs.version }}.dxt release-assets/
        
        # Copy documentation
        cp build-dxt/assets/README.md release-assets/
        cp build-dxt/assets/check-prereqs.sh release-assets/
        
        # Make check-prereqs executable
        chmod +x release-assets/check-prereqs.sh
        
        # List what we're releasing
        echo "Release assets:"
        ls -la release-assets/
        
    - name: Generate release notes
      if: steps.version.outputs.is_release == 'true'
      id: release_notes
      run: |
        VERSION=${{ steps.version.outputs.version }}
        cat > release-notes.md << EOF
        # Quilt MCP DXT v${VERSION}
        
        ## What's New
        
        This release includes the Quilt MCP Desktop Extension (DXT) for Claude Desktop.
        
        ## Installation
        
        1. **Download the assets** from this release
        2. **Run prerequisites check**: \`./check-prereqs.sh\`
        3. **Install the DXT**: Double-click \`quilt-mcp-${VERSION}.dxt\`
        4. **Configure catalog domain** in Claude Desktop settings
        
        ## What's Included
        
        - \`quilt-mcp-${VERSION}.dxt\` - The MCP extension for Claude Desktop
        - \`README.md\` - Installation and usage instructions  
        - \`check-prereqs.sh\` - Prerequisites validation script
        
        ## System Requirements
        
        - **Python 3.11+** (required for the MCP server)
        - **AWS credentials** (for accessing your Quilt data)
        - **Claude Desktop** (latest version recommended)
        - **Quilt catalog domain** (contact your admin if unsure)
        
        ## Security
        
        - Uses your existing AWS credentials - no additional authentication needed
        - Runs locally on your machine - no external services involved
        - Your data stays in your AWS environment
        
        For detailed instructions, see the included README.md file.
        EOF
        
        echo "release_notes<<EOF" >> $GITHUB_OUTPUT
        cat release-notes.md >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
    - name: Create GitHub Release
      if: steps.version.outputs.is_release == 'true'
      uses: softprops/action-gh-release@v2
      with:
        name: "Quilt MCP DXT v${{ steps.version.outputs.version }}"
        body: ${{ steps.release_notes.outputs.release_notes }}
        files: |
          release-assets/quilt-mcp-${{ steps.version.outputs.version }}.dxt
          release-assets/README.md
          release-assets/check-prereqs.sh
        draft: false
        prerelease: ${{ contains(steps.version.outputs.version, '-') }}
        generate_release_notes: false
        
    - name: Output build info
      run: |
        echo "✅ All tests passed!"
        if [[ "${{ steps.version.outputs.is_release }}" == "true" ]]; then
          echo "✅ Release created successfully!"
          echo "Version: ${{ steps.version.outputs.version }}"
          echo "Tag: ${{ github.ref }}"
          echo "Release URL: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
        else
          echo "✅ Feature branch DXT built successfully!"
          echo "Version: ${{ steps.version.outputs.version }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "DXT artifact uploaded for testing and validation"
          echo "Download from: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        fi