name: Nightly PR (Develop ➜ Staging)

on:
  workflow_dispatch: # Allow manual triggering

jobs:
  create-staging-pr:
    name: Create PR from develop to staging
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: develop

    - name: Create PR to staging
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: staging
        branch: develop-to-staging-${{ github.run_number }}
        title: "🚀 Nightly: Develop → Staging (Build #${{ github.run_number }})"
        body: |
          Automated nightly PR to merge latest develop into staging.
          
          - Source: develop
          - Target: staging
          - Trigger: ${{ github.event_name }}
        labels: |
          automated
          nightly-build
          develop-to-staging
        assignees: |
          QuiltSimon
        reviewers: |
          QuiltSimon