# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Pull Request Validation

on:
  pull_request:
    branches: ['**']
  push:
    tags: ['v*-dev-*']
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup build environment
      uses: ./.github/actions/setup-build-env
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run PR tests
      uses: ./.github/actions/run-tests
      with:
        test-target: 'test-ci'
        artifact-name: 'test-results-pr'
        python-version: '3.11'
      env:
        # AWS credentials for tests that need them
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}

        # Quilt configuration
        QUILT_DEFAULT_BUCKET: ${{ secrets.QUILT_DEFAULT_BUCKET }}
        QUILT_CATALOG_URL: ${{ secrets.QUILT_CATALOG_URL }}
        QUILT_TEST_PACKAGE: ${{ secrets.QUILT_TEST_PACKAGE }}
        QUILT_TEST_ENTRY: ${{ secrets.QUILT_TEST_ENTRY }}

    - name: Debug GitHub context for dev-release
      run: |
        echo "=== GitHub Context Debug ==="
        echo "Event: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
        echo "Ref type: ${{ github.ref_type }}"
        echo "Ref name: ${{ github.ref_name }}"
        echo "Head ref: ${{ github.head_ref }}"
        echo "Base ref: ${{ github.base_ref }}"
        echo "SHA: ${{ github.sha }}"
        echo "=== Tag Detection ==="
        echo "Starts with refs/tags/v: ${{ startsWith(github.ref, 'refs/tags/v') }}"
        echo "Contains -dev-: ${{ contains(github.ref, '-dev-') }}"
        echo "Combined condition: ${{ startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-dev-') }}"

  dev-release:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 30
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-dev-')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup build environment
      uses: ./.github/actions/setup-build-env
      with:
        python-version: '3.11'
        include-nodejs: 'true'
    - name: Debug dev-release context
      run: |
        echo "=== Dev-Release Context Debug ==="
        echo "Event: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
        echo "Ref type: ${{ github.ref_type }}"
        echo "Ref name: ${{ github.ref_name }}"
        echo "SHA: ${{ github.sha }}"
        echo "=== Condition Check ==="
        echo "startsWith(github.ref, 'refs/tags/v'): ${{ startsWith(github.ref, 'refs/tags/v') }}"
        echo "contains(github.ref, '-dev-'): ${{ contains(github.ref, '-dev-') }}"
        echo "Combined condition result: ${{ startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-dev-') }}"

    - name: Extract version from tag
      id: version
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        echo "tag_version=$TAG_VERSION" >> $GITHUB_OUTPUT
        echo "Dev Tag Version: $TAG_VERSION"
    - name: Create dev release
      uses: ./.github/actions/create-release
      with:
        tag-version: ${{ steps.version.outputs.tag_version }}
        pypi-token: ${{ secrets.PYPI_TOKEN }}
        pypi-repository-url: https://test.pypi.org/legacy/
