name: Release

on:
  push:
    tags: ['v*']

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Set up Python
      run: uv python install 3.11
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
      
    - name: Install DXT CLI
      run: npm install -g @anthropic-ai/dxt
      
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          ~/.npm
        key: ${{ runner.os }}-deps-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-deps-
      
    - name: Build DXT package
      run: make dxt
      
    - name: Validate DXT package
      run: make validate-dxt

    - name: Extract version from tag
      id: version
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        echo "tag_version=$TAG_VERSION" >> $GITHUB_OUTPUT
        echo "Tag Version: $TAG_VERSION"

    - name: Extract manifest version
      id: manifest
      run: |
        MANIFEST_VERSION=$(python3 -c "import json; print(json.load(open('tools/dxt/assets/manifest.json'))['version'])")
        echo "manifest_version=$MANIFEST_VERSION" >> $GITHUB_OUTPUT
        echo "Manifest Version: $MANIFEST_VERSION"

    - name: Create release bundle
      run: |
        mkdir -p release-bundle
        cp tools/dxt/dist/quilt-mcp-${{ steps.manifest.outputs.manifest_version }}.dxt release-bundle/
        cp tools/dxt/assets/README.md release-bundle/
        cp tools/dxt/assets/check-prereqs.sh release-bundle/
        cd release-bundle
        zip -r ../quilt-mcp-${{ steps.version.outputs.tag_version }}-bundle.zip .
        cd ..
        echo "Bundle created: quilt-mcp-${{ steps.version.outputs.tag_version }}-bundle.zip"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: "Quilt MCP DXT v${{ steps.version.outputs.tag_version }}"
        files: |
          tools/dxt/dist/quilt-mcp-${{ steps.manifest.outputs.manifest_version }}.dxt
          tools/dxt/assets/README.md
          tools/dxt/assets/check-prereqs.sh
          quilt-mcp-${{ steps.version.outputs.tag_version }}-bundle.zip
        draft: false
        prerelease: ${{ contains(steps.version.outputs.tag_version, '-') }}
        generate_release_notes: true
        
    - name: Upload DXT artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dxt-package
        path: tools/dxt/dist/*.dxt
        retention-days: 90