name: Release

on:
  push:
    tags: ['v*']

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Set up Python
      run: uv python install 3.11
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
      
    - name: Install DXT CLI
      run: npm install -g @anthropic-ai/dxt
      
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          ~/.npm
        key: ${{ runner.os }}-deps-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-deps-
      
    - name: Build DXT package
      run: make dxt
      
    - name: Validate DXT package
      run: make validate-dxt

    - name: Extract version from tag
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: "Quilt MCP DXT v${{ steps.version.outputs.version }}"
        files: |
          tools/dxt/dist/quilt-mcp-${{ steps.version.outputs.version }}.dxt
          tools/dxt/assets/README.md
          tools/dxt/assets/check-prereqs.sh
        draft: false
        prerelease: ${{ contains(steps.version.outputs.version, '-') }}
        generate_release_notes: true
        
    - name: Upload DXT artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dxt-package
        path: tools/dxt/dist/*.dxt
        retention-days: 90