name: Production Release

on:
  workflow_run:
    workflows: ["Main Branch Validation"]
    types: [completed]
    branches: [main]
  push:
    tags: ['v*']
    tags-ignore: ['v*-dev-*']
  workflow_dispatch:

jobs:
  prod-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # Workflow_run takes precedence: only run if main tests passed OR direct emergency tag push
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-dev-')) || github.event_name == 'workflow_dispatch' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup build environment
      uses: ./.github/actions/setup-build-env
      with:
        python-version: '3.11'
        include-nodejs: 'true'

    - name: Extract version from tag (if tag push)
      if: startsWith(github.ref, 'refs/tags/v')
      id: version
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        echo "tag_version=$TAG_VERSION" >> $GITHUB_OUTPUT
        echo "Tag Version: $TAG_VERSION"

    - name: Create production release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: ./.github/actions/create-release
      with:
        tag-version: ${{ steps.version.outputs.tag_version }}

    - name: Create release from main branch
      if: github.event_name == 'workflow_run' || github.event_name == 'workflow_dispatch'
      run: |
        echo "Creating production release from successful main branch validation..."
        make release