name: Unit Tests

# Fast unit tests with mocks - run on every PR
# For integration tests with real AWS, see integration-test.yml

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Add overall job timeout
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      timeout-minutes: 2
      
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
      timeout-minutes: 3
        
    - name: Set up Python
      run: uv python install ${{ matrix.python-version }}
      timeout-minutes: 3
            
    - name: Run unit and AWS tests
      run: make -C app test-ci-with-aws
      timeout-minutes: 15
      env:
        UVRUN: uv run
        # Use real AWS credentials from repository secrets
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}
        
        # Quilt-specific settings from repository secrets
        QUILT_DEFAULT_BUCKET: ${{ secrets.QUILT_DEFAULT_BUCKET }}
        QUILT_CATALOG_URL: ${{ secrets.QUILT_CATALOG_URL }}
        QUILT_TEST_PACKAGE: ${{ secrets.QUILT_TEST_PACKAGE }}
        QUILT_TEST_ENTRY: ${{ secrets.QUILT_TEST_ENTRY }}
        
        # Test configuration
        UNIT_TEST_MODE: "false"
