name: Unit Tests

# Fast unit tests with mocks - run on every PR
# For integration tests with real AWS, see integration-test.yml

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Add overall job timeout
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      timeout-minutes: 2
      
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
      timeout-minutes: 3
        
    - name: Set up Python
      run: uv python install ${{ matrix.python-version }}
      timeout-minutes: 3
            
    - name: Run unit tests
      run: make test-ci
      timeout-minutes: 10
      env:
        UVRUN: uv run
        # No AWS credentials - unit tests should use mocks
        UNIT_TEST_MODE: "true"
        # Note: AWS credentials available as organization secrets for integration tests
