name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Set up Python
      run: uv python install 3.11
      
    - name: Install dependencies
      run: uv sync --group test
      
    - name: Run tests
      run: uv run python -m pytest tests/ -v --tb=short
      
    - name: Check code formatting (optional)
      run: uv run ruff check . || true
      continue-on-error: true

  # Optional: Test Docker build for Lambda compatibility
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Test Docker build
      run: |
        docker build --platform linux/amd64 -t quilt-mcp-test .
        # Test that pydantic_core can be imported
        docker run --rm --entrypoint="" quilt-mcp-test \
          python -c "import pydantic_core._pydantic_core; print('✅ pydantic_core works')"
